name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install and Build
        run: |
          npm ci
          CI=false npm run build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CERTIFICAGE }}'
          channelId: live
          projectId: certificage
