name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install and Build
        run: |
          npm ci
          CI=false REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }} REACT_APP_DATABASE_URL=${{ secrets.REACT_APP_DATABASE_URL }} REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }} REACT_APP_STORAGE_BUCKET=${{ secrets.REACT_APP_STORAGE_BUCKET }} REACT_APP_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} REACT_APP_APP_ID=${{ secrets.REACT_APP_APP_ID }}  npm run build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CERTIFICAGE }}'
          channelId: live
          projectId: certificage
